VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "GroupTwoSides"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Struct
Option Explicit

'===============================================================================

Public Fronts As Collection
Public Backs As Collection

'===============================================================================
